name: CI Pipeline Build API

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: fianu-prod   # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
  GOPRIVATE: github.com/fianulabs/*
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:

  api:
    name: XD Banking API
    uses: fianulabs/tools/.github/workflows/golang_pipeline.yaml@main
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      app-code: DBX
      artifact-name: xd-banking-api
      artifact-version: 1.0.0
      working-directory: ./xd-banking-api
      build-path: ko://github.com/badgercorp/xd-banking-api/cmd/api

  stage-release:
    needs: [ api ]
    name: Release
    uses: fianulabs/tools/.github/workflows/release.yaml@main
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      tag: ${{ needs.api.outputs.digest }}
      path: envs/rnd/values-image.yaml
      deploy: fianulabs/investments-unlimited-deploy