name: CI Pipeline Build API

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: fianu-prod   # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
  GOPRIVATE: github.com/fianulabs/*
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  consulta:
    name: XD Banking API
    uses: fianulabs/tools/.github/workflows/golang_pipeline.yaml@main
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      app-code: SW13172
      artifact-name: xd-banking-api
      artifact-version: 1.0.0
      working-directory: ./xd-banking-api
      build-path: ko://github.com/badgercorp/xd-banking-api/cmd/api