name: CI SAST Scan

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: fianu-prod  # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-test # TODO: update to deployment name
  FIANU_ARTIFACT: xd-banking-api
  FIANU_VERSION: ${{ secrets.FIANU_VERSION }}
  FIANU_HOST: ${{ secrets.FIANU_HOST }}
  FIANU_KEY: ${{ secrets.FIANU_COSIGN_KEY }}
  REKOR_HOST: ${{ secrets.REKOR_URL }}
  GITHUB_CONTEXT: ${{ toJSON(github) }}

jobs:

  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup fianu
        uses: fianulabs/actions@main
        with:
          version: ${{ env.FIANU_VERSION }}

      - name: Auto Set Build Version
        run: |-
          export FIANU_ARTIFACT_VERSION="$(fianu get version)"
          echo "FIANU_ARTIFACT_VERSION=$FIANU_ARTIFACT_VERSION" >> $GITHUB_ENV

  api-tooling:
    name: Security Tooling
    uses: fianulabs/tools/.github/workflows/build.yaml@main
    secrets: inherit
    with:
      working-directory: ./xd-banking-api
      project-type: golang
      fianu-artifact: xd-banking-api

  ui-tooling:
    name: Security Tooling
    uses: fianulabs/tools/.github/workflows/build.yaml@main
    secrets: inherit
    with:
      working-directory: ./xd-banking-ui
      project-type: node
      fianu-artifact: xd-banking-ui

  mock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup fianu
        uses: fianulabs/actions@main
        with:
          version: ${{ env.FIANU_VERSION }}

      - name: Auto Set Build Version
        run: |-
          export FIANU_ARTIFACT_VERSION="$(fianu get version)"
          echo "FIANU_ARTIFACT_VERSION=$FIANU_ARTIFACT_VERSION" >> $GITHUB_ENV

      - name: Mock Captures
        env:
          FIANU_USERNAME: ${{ secrets.FIANU_USERNAME }}
          FIANU_CLIENT_ID: ${{ secrets.FIANU_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_CLIENT_SECRET }}
        run: |-
          fianu capture artifact --input cx.xml --type checkmarx --source plugin
          fianu capture artifact --input bd.json --type blackduck --source rapidscan
