# workflow to run anything that needs to run before every other workflow
name: Pre-Flow Actionss

on:
  push:
    branches: [main]

env:
  POLICY_FILE: policy.yaml
  BADGER_VERSION: 0.2.6
  BADGER_KEY: k8s://default/cosign
  REKOR_HOST: ${{ secrets.REKOR_URL }}

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      - name: badger
        uses: nick-invision/private-action-loader@v3
        with:
          pal-repo-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pal-repo-name: badgercorp/actions
          version: ${{ env.BADGER_VERSION }}
          authorization: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Deploy Policy
        run: |-
          badger attestor wrap --key $BADGER_KEY --rekor-url $REKOR_HOST --output-file deploy.policy.json --step deploy.policy \
          -- badger policy register resource -c repository -p $POLICY_FILE
          
          badger attestor hash --path deploy.policy.json

