# workflow to run anything that needs to run before every other workflow
name: Pre-Flow Actionss

on:
  push:
    branches: [main]

env:
  POLICY_FILE: policy.yaml
  BADGER_VERSION: 0.2.3
  BADGER_KEY: k8s://default/cosign
  REKOR_HOST: ${{ secrets.REKOR_URL }}

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: badger
        uses: nick-invision/private-action-loader@v3
        with:
          pal-repo-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pal-repo-name: badgercorp/actions
          version: ${{ env.BADGER_VERSION }}
          authorization: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Deploy Policy
        run: |-
          badger attestor wrap \ 
          --key $BADGER_KEY --rekor-url $REKOR_HOST --step $GITHUB_JOB.deploy.policy --output-file deploy.policy.json \
          -- badger policy register resource -c repository -p $POLICY_FILE
          
          badger attestor hash --path deploy.policy.json

