# workflow to run anything that needs to run before every other workflow
name: Pre-Flow Actionss

on:
  push:
    branches: [main]

env:
  POLICY_FILE: policy.yaml
  BADGER_VERSION: 0.2.10
  GKE_CLUSTER: badgercorp  # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: badger
        uses: nick-invision/private-action-loader@v3
        with:
          pal-repo-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pal-repo-name: badgercorp/actions
          version: ${{ env.BADGER_VERSION }}
          authorization: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Deploy Policy
        run: |-
          badger policy register resource -c repository -p $POLICY_FILE

