name: CI Pipeline Sonar Scan

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./xd-banking-api

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: fianu-prod  # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-test # TODO: update to deployment name
  ARTIFACT: xd-banking-api
  FIANU_VERSION: ${{ secrets.FIANU_VERSION }}
  FIANU_HOST: ${{ secrets.FIANU_HOST }}

jobs:
  sonarqube:

    name: Run SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -coverprofile=cov.out -v ./... -json > report.json

      - name: setup fianu
        uses: fianulabs/actions@main
        with:
          version: ${{ env.FIANU_VERSION }}

      - name: Setup
        env:
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GITHUB_SERVER_URL: ${{ env.GITHUB_SERVER_URL }}
          ARTIFACT: ${{ env.ARTIFACT }}
        run: |-
          export FIANU_ARTIFACT_VERSION="$(fianu get version)"
          echo "FIANU_ARTIFACT_VERSION=$FIANU_ARTIFACT_VERSION" >> $GITHUB_ENV
          echo "FIANU_ARTIFACT=$ARTIFACT" >> $GITHUB_ENV
          echo "GITHUB_SHA=$GITHUB_SHA" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" >> $GITHUB_ENV
          echo "GITHUB_SERVER_URL=$GITHUB_SERVER_URL" >> $GITHUB_ENV

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://sonarqube.sonarqube.35.232.161.16.sslip.io
          PROJECT_KEY: ${{ env.GITHUB_REPOSITORY_ID }}
          PROJECT_NAME: aesthetic_change
        with:
          args: >
            -Dsonar.sources=.
            -Dsonar.projectKey=${{ env.PROJECT_KEY }}
            -Dsonar.projectName=${{ env.PROJECT_NAME }}
            -Dsonar.projectVersion=${{ env.FIANU_ARTIFACT_VERSION }}
            -Dsonar.go.coverage.reportPaths=/github/workspace/xd-banking-api/cov.out
            -Dsonar.go.tests.reportPaths=/github/workspace/xd-banking-api/report.json
            -Dsonar.exclusions=**/*_test.go,**/vendor/**,**/testdata/*,xd-banking-ui/*,**/xd-banking-ui/**,xd-banking-ui/**/*
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.test.exclusions=**/vendor/**,xd-banking-ui/*,**/xd-banking-ui/**,xd-banking-ui/**/*
            -Dsonar.analysis.version=${{ env.FIANU_ARTIFACT_VERSION }}
            -Dsonar.analysis.commit=${{ env.GITHUB_SHA }}
            -Dsonar.analysis.buildURI=${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/commit/${{ env.GITHUB_SHA }}
            -Dsonar.analysis.artifact=${{ env.FIANU_ARTIFACT }}

