name: CI Pipeline Sonar Scan

on:
  workflow_run:
    workflows:
      - Pre-Flow Actions
    branches: [main]
    types:
      - completed

defaults:
  run:
    working-directory: ./xd-banking-api

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: badgercorp  # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-test # TODO: update to deployment name
  ARTIFACT: xd-banking-api
  BADGER_VERSION: 0.2.12

jobs:
  sonarqube:

    name: Run SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -coverprofile=cov.out -v ./... -json > report.json

      - name: badger
        uses: nick-invision/private-action-loader@v3
        with:
          pal-repo-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pal-repo-name: badgercorp/actions
          version: ${{ env.BADGER_VERSION }}
          authorization: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Setup
        run: |-
          badger set-version
          export VERSION="$(badger get version)"
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: http://sonarqube.sonarqube.34.132.74.168.sslip.io
          login: 11be8002a77e1ed89637f117cb713cc72bbc9ce1
          projectKey: xd-banking-app                    # ${{ env.ORGANIZATION }}
          projectName: badgercorp   # ${{ env.COMPONENT }}
          projectVersion: ${{ env.VERSION }}