#name: CI Pipeline Sonar Scan
#
#on:
#  push:
#    branches: [ main ]
#
#defaults:
#  run:
#    working-directory: ./xd-banking-api
#
#env:
#  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
#  GKE_CLUSTER: fianu-prod  # TODO: update to cluster name
#  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
#  DEPLOYMENT_NAME: gke-test # TODO: update to deployment name
#  ARTIFACT: xd-banking-api
#  FIANU_VERSION: ${{ secrets.FIANU_VERSION }}
#  FIANU_HOST: ${{ secrets.FIANU_HOST }}
#
#jobs:
#  sonarqube:
#
#    name: Run SonarQube Scan
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.17
#
#      - name: Build
#        run: go build -v ./...
#
#      - name: Test
#        run: go test -coverprofile=cov.out -v ./... -json > report.json
#
#      - name: setup fianu
#        uses: nick-invision/private-action-loader@v3
#        with:
#          pal-repo-token: ${{ secrets.GH_ACCESS_TOKEN }}
#          pal-repo-name: fianulabs/actions
#          version: ${{ env.FIANU_VERSION }}
#          authorization: ${{ secrets.GH_ACCESS_TOKEN }}
#
#      - name: Setup
#        run: |-
#          export FIANU_BUILD_VERSION="$(fianu get version)"
#          echo "FIANU_BUILD_VERSION=$FIANU_BUILD_VERSION" >> $GITHUB_ENV
#
#      - name: SonarQube Scan
#        uses: kitabisa/sonarqube-action@v1.2.0
#        with:
#          host: http://sonarqube.sonarqube.35.232.161.16.sslip.io
#          login: ${{ secrets.SONAR_USERNAME }}
#          password: ${{ secrets.SONAR_PASSWORD }}
#          projectKey: xd-banking-app                    # ${{ env.ORGANIZATION }}
#          projectName: fianulabs   # ${{ env.COMPONENT }}
#          projectVersion: ${{ env.FIANU_BUILD_VERSION }}
#
