name: XD Banking App CI Pipeline

on:
  push:
    branch:
      - main

env:
  ARTIFACT_NAME: xd-banking-api

jobs:
  setup:
    name: Start Fianu Pipeline Session
    uses: fianulabs/tools/.github/workflows/pipeline.yaml@main
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      app-code: SW99TEST
      fianu-artifact: xd-banking-api

  close:
    name: Fianu Pipeline Close
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.auto-version.outputs.version }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup fianu
        uses: fianulabs/actions@main
        with:
          version: ${{ secrets.FIANU_VERSION }}

      - name: Auto Set Build Version
        id: auto-version
        run: |-
          export FIANU_ARTIFACT_VERSION="$(fianu get version)"
          echo "FIANU_ARTIFACT_VERSION=$FIANU_ARTIFACT_VERSION" >> $GITHUB_ENV
          echo "version=$FIANU_ARTIFACT_VERSION" >> $GITHUB_OUTPUT

      - name: Session Start
        run: |-
          fianu session close
        env:
          FIANU_APP_CODE: SW99TEST
          FIANU_USERNAME: ${{ secrets.FIANU_USERNAME }}
          FIANU_CLIENT_ID: ${{ secrets.FIANU_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_CLIENT_SECRET }}
          FIANU_HOST: ${{ secrets.FIANU_HOST }}