name: CI Pipeline Build UI

on:
  push:
    tags:
      - '**'
      - '*'
    branches:
      - main

env:
  FIANU_ARTIFACT_NAME: xd-banking-ui

jobs:
  setup:
    name: Start Fianu Pipeline Session
    uses: fianulabs/tools/.github/workflows/pipeline.yaml@main
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      app-code: dbx
      fianu-artifact: xd-banking-ui

  prepare:
    name: Run Preparation
    runs-on: ubuntu-latest
    needs: [ setup ]
    outputs:
      artifact-name: ${{ steps.set-outputs.outputs.ARTIFACT_NAME }}
      artifact-version: ${{ steps.set-outputs.outputs.ARTIFACT_VERSION }}
    steps:
      - name: Outputs
        id: set-outputs
        run: |-
          echo "ARTIFACT_NAME=${{ env.FIANU_ARTIFACT_NAME }}" >> $GITHUB_OUTPUT
          echo "ARTIFACT_VERSION=${{ needs.setup.outputs.version }}" >> $GITHUB_OUTPUT

  container:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: [ prepare ]
    defaults:
      run:
        working-directory: ./xd-banking-ui

    outputs:
      digest: ${{ steps.digest.outputs.digest }}

    permissions:
      id-token: write
      contents: write
      packages: write
      actions: write

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup fianu
        uses: fianulabs/actions@main
        with:
          version: ${{ secrets.FIANU_VERSION }}

      # Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_HELM_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker us-central1-docker.pkg.dev


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install


      - name: Cypress run
        uses: cypress-io/github-action@v4
        id: cypress
        continue-on-error: true
        timeout-minutes: 10
        with:
          working-directory: xd-banking-ui
          install: false
          record: true
          command: npm run test:e2e:ci

      - env:
          FIANU_ARTIFACT: ${{ needs.prepare.outputs.artifact-name }}
          FIANU_USERNAME: ${{ secrets.FIANU_USERNAME }}
          FIANU_CLIENT_ID: ${{ secrets.FIANU_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_CLIENT_SECRET }}
          FIANU_HOST: ${{ secrets.FIANU_HOST }}
        run: |-
          fianu capture evidence --input cypress/results/mochawesome.json --type testing --source mocha

      - name: Build and Publish
        id: digest
        run: |-
          npm run build

          docker build . -t "${{ secrets.DOCKER_IMAGE_LOCATION }}/${{ needs.prepare.outputs.artifact-name }}:${{ needs.prepare.outputs.artifact-version }}" -t "${{ secrets.DOCKER_IMAGE_LOCATION }}/${{ needs.prepare.outputs.artifact-name }}:latest"
          docker push "${{ secrets.DOCKER_IMAGE_LOCATION }}/${{ needs.prepare.outputs.artifact-name }}:${{ needs.prepare.outputs.artifact-version }}"
          docker push "${{ secrets.DOCKER_IMAGE_LOCATION }}/${{ needs.prepare.outputs.artifact-name }}:latest"

          IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "${{ secrets.DOCKER_IMAGE_LOCATION }}/${{ needs.prepare.outputs.artifact-name }}:${{ needs.prepare.outputs.artifact-version }}" | cut -d@ -f2)
          echo "digest=$IMAGE_DIGEST" >> $GITHUB_OUTPUT

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: us-central1-c
          credentials: ${{ secrets.GKE_HELM_SA_KEY }}

  security:
    name: Fianu Security
    uses: fianulabs/tools/.github/workflows/security.yaml@main
    secrets: inherit
    needs: [ prepare, container ]
    with:
      working-directory: ./xd-banking-ui
      project-type: node
      fianu-artifact: ${{ needs.prepare.outputs.artifact-name }}
      artifact-name: ${{ needs.prepare.outputs.artifact-name }}
      artifact-version: ${{ needs.prepare.outputs.artifact-version }}

  fianu-container-metadata:
    name: Fianu Container Metadata Job
    uses: fianulabs/tools/.github/workflows/container_metadata.yaml@main
    secrets: inherit
    needs: [ prepare, container ]
    permissions:
      id-token: write
      contents: write
      packages: write
      actions: write
    with:
      working-directory: ./xd-banking-ui
      oci-artifact: "${{ needs.prepare.outputs.artifact-name }}:${{ needs.prepare.outputs.artifact-version }}"

  fianu-signed-artifact:
    name: Fianu Signed Artifact
    uses: fianulabs/tools/.github/workflows/artifact_signing.yaml@main
    secrets: inherit
    needs: [ prepare, container, fianu-container-metadata ]
    permissions:
      id-token: write
      contents: write
      packages: write
      actions: write
    with:
      working-directory: ./xd-banking-ui
      oci-artifact: "${{ needs.prepare.outputs.artifact-name }}:${{ needs.prepare.outputs.artifact-version }}"
      oci-artifact-name: ${{ needs.prepare.outputs.artifact-name }}
      oci-artifact-digest: ${{ needs.container.outputs.digest }}