name: CI Pipeline Build UI

on:
  workflow_run:
    workflows:
      - Pre-Flow Actions
    branches: [main]
    types:
      - completed

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: badgercorp  # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-test # TODO: update to deployment name
  ARTIFACT: xd-banking-ui
  BADGER_VERSION: 0.3.5
  FIANU_KEY: k8s://default/cosign
  REKOR_HOST: ${{ secrets.REKOR_URL }}
  GITHUB_CONTEXT: ${{ toJSON(github) }}

defaults:
  run:
    working-directory: ./xd-banking-ui

jobs:
  init:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: badger
        uses: nick-invision/private-action-loader@v3
        with:
          pal-repo-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pal-repo-name: badgercorp/actions
          version: ${{ env.BADGER_VERSION }}
          authorization: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Capture
        run: |-
          badger take snapshot -o snapshot.json
          badger capture data --type build --input snapshot.json

  testing:
    runs-on: ubuntu-18.04
    name: Install, Test, Build, Scan & Publish
    strategy:
      matrix:
        node-version: [ 16.x ]

    permissions:
      id-token: write # Needed for keyless.
      contents: read
      # actions permissions are needed to read info on the workflow and
      # workflow run.
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: badger
        uses: nick-invision/private-action-loader@v3
        with:
          pal-repo-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pal-repo-name: badgercorp/actions
          version: ${{ env.BADGER_VERSION }}
          authorization: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Setup
        run: |-
          badger set-version
          export VERSION="$(badger get version)"
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v4
        id: cypress
        continue-on-error: true
        timeout-minutes: 10
        with:
          working-directory: xd-banking-ui
          install: false
          record: true
          command: npm run test:e2e:ci

      - run: |-
          badger capture data \
            --type testing --input cypress/results/mochawesome.json --artifact "$ARTIFACT:$VERSION" --version $VERSION --key $FIANU_KEY --rekor-url $REKOR_HOST --attest

      - name: Build UI
        run: npm run build

      - name: Build UI Image
        run: |-
          badger attestor wrap --step docker.build --key $FIANU_KEY --rekor-url $REKOR_HOST --output-file result.json -- \
            docker build \
            --tag "gcr.io/$PROJECT_ID/$ARTIFACT:$VERSION" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
                    
          ARTIFACT_STATEMENTS=$(badger attestor hash --path result.json)
          echo "ARTIFACT_STATEMENTS=$ARTIFACT_STATEMENTS" >> $GITHUB_ENV

      - uses: anchore/scan-action/download-grype@v3
        id: grype
        with:
          grype-version: v0.43.0

      - run: |-
          badger attestor wrap --step grype.scan --key $FIANU_KEY --rekor-url $REKOR_HOST --output-file result.json -- \
            ${{steps.grype.outputs.cmd}} -o json --file grype_scan.json gcr.io/$PROJECT_ID/$ARTIFACT:$VERSION
          
          GRYPE_STATEMENTS=$(badger attestor hash --path result.json)
          echo "GRYPE_STATEMENTS=$GRYPE_STATEMENTS" >> $GITHUB_ENV

      - run: |-
          COMBINED="$ARTIFACT_STATEMENTS,$GRYPE_STATEMENTS"
          badger capture data \
            --statements $COMBINED --key $FIANU_KEY --type containerscan --rekor-url $REKOR_HOST --attest  --input grype_scan.json --version=$VERSION

      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.10.1'

      - name: Publish Artifactn Image
        run: |-
          IMAGE=$ARTIFACT

          badger attestor wrap --step docker.push --key $FIANU_KEY --rekor-url $REKOR_HOST --output-file result.json -- \
            docker push "gcr.io/$PROJECT_ID/$IMAGE:$VERSION"
          PUBLISH_STATEMENTS=$(badger attestor hash --path result.json)
          
          badger attestor wrap --step cosign.sign --key $FIANU_KEY --rekor-url $REKOR_HOST --output-file result.json -- \
            cosign sign -a version=$VERSION -a commit=$GITHUB_SHA --key k8s://default/cosign "gcr.io/$PROJECT_ID/$IMAGE:$VERSION"
          PUBLISH_STATEMENTS=$PUBLISH_STATEMENTS,$(badger attestor hash --path result.json)
          
          cosign verify --key k8s://default/cosign "gcr.io/$PROJECT_ID/$IMAGE:$VERSION"
          
          badger attestor wrap --step cosign.generate --key $FIANU_KEY --rekor-url $REKOR_HOST --output-file result.json -- \
            cosign generate -a version=$VERSION -a commit=$GITHUB_SHA --output-file=sig.json "gcr.io/$PROJECT_ID/$IMAGE:$VERSION"
          PUBLISH_STATEMENTS=$PUBLISH_STATEMENTS,$(badger attestor hash --path result.json)
          
          echo "PUBLISH_STATEMENTS=$PUBLISH_STATEMENTS" >> $GITHUB_ENV

      - name: Capture Sign
        run: |-
          COMBINED="$ARTIFACT_STATEMENTS,$PUBLISH_STATEMENTS"
          badger capture data \
            --type cosign --statements $COMBINED --input sig.json --version $VERSION --key $FIANU_KEY --rekor-url $REKOR_HOST --attest

      - name: Create and Publish Artifact SBOM
        uses: anchore/sbom-action@v0
        with:
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.ARTIFACT }}:${{ env.VERSION }}
          output-file: xd-banking-ui/sbom.spdx.json

      - run: |-
          badger capture data \
            --type sbom --input sbom.spdx.json --version $VERSION --key $FIANU_KEY --rekor-url $REKOR_HOST --attest