name: CI Pipeline Build UI

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: fianu-prod   # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
  DEPLOYMENT_NAME: docs # TODO: update to deployment name
  REPOSITORY: badgercorp # TODO: update to Artifact Registry docker repository
  GOPRIVATE: github.com/fianulabs/*
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  FIANU_ARTIFACT_NAME: fianu

jobs:
  fianu:
    name: Fianu Pipeline Setup
    uses: fianulabs/tools/.github/workflows/pipeline.yaml@main
    secrets: inherit
    with:
      app-code: SW11094
      fianu-artifact: fianu

  prepare:
    name: Run Preparation
    runs-on: ubuntu-latest
    needs: [ fianu ]
    outputs:
      artifact-name: ${{ steps.set-outputs.outputs.ARTIFACT_NAME }}
      artifact-version: ${{ steps.set-outputs.outputs.ARTIFACT_VERSION }}
    steps:
      - name: Outputs
        id: set-outputs
        run: |-
          echo "ARTIFACT_NAME=${{ env.FIANU_ARTIFACT_NAME }}" >> $GITHUB_OUTPUT
          echo "ARTIFACT_VERSION=${{ needs.fianu.outputs.version }}" >> $GITHUB_OUTPUT

  container:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: [ prepare ]
    defaults:
      run:
        working-directory: ./xd-banking-ui

    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_HELM_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker us-central1-docker.pkg.dev


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Build and Publish
        run: |-
          npm run build

          docker build . -t "${{ secrets.DOCKER_IMAGE_LOCATION }}/${{ needs.prepare.outputs.artifact-name }}:${{ needs.prepare.outputs.artifact-version }}"
          docker push "${{ secrets.DOCKER_IMAGE_LOCATION }}/${{ needs.prepare.outputs.artifact-name }}:${{ needs.prepare.outputs.artifact-version }}"

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_HELM_SA_KEY }}

  security:
    name: Fianu Security
    uses: fianulabs/tools/.github/workflows/security.yaml@main
    secrets: inherit
    needs: [ prepare, container ]
    with:
      working-directory: ./xd-banking-ui
      project-type: node
      fianu-artifact: ${{ needs.prepare.outputs.artifact-name }}
      artifact-name: ${{ needs.prepare.outputs.artifact-name }}
      artifact-version: ${{ needs.prepare.outputs.artifact-version }}

  fianu-signed-artifact:
    name: Fianu Signed Artifact
    uses: fianulabs/tools/.github/workflows/artifact_signing.yaml@main
    secrets: inherit
    needs: [ prepare, container ]
    permissions:
      id-token: write
      contents: read
    with:
      working-directory: ./xd-banking-ui
      oci-artifact: "${{ needs.prepare.outputs.artifact-name }}:${{ needs.prepare.outputs.artifact-version }}"
